language: java
install: true

cache:
  directories:
    - "$HOME/.m2"

jobs:
  include:
    # 1.1 Tests
    - stage: test
      jdk: openjdk11
      script: mvn verify
      env: VERIFY=true

    # 1.2 Coverage
    - stage: test
      jdk: openjdk11
      script: mvn jacoco:prepare-agent verify jacoco:report coveralls:report
      env: COVERAGE=true

    # 1.3 Javadoc
    - jdk: openjdk11
      env: JAVADOC=true
      script:
        - mvn javadoc:jar

branches:
  only:
  - master
  - sonarqube-v7
  - sonarqube-v8
  - sonarqube-v9